apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust-policy
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      - path: /tmp/testfile.txt
        severity: 5
        action: Block

